### ISSUE TITLE
Rename tintColor properties to be more inline with UIProgressView

### ISSUE THREAD

**Issue by ekurutepe** [darrarski/DRCircularProgress-iOS#6]
First of all, thanks for this really well done progress view!

We are using this in our project and would like to suggest to deprecate `progressColor` and `alternativeColor` to rename them to `progressTintColor` and `trackTintColor` respectively in order to make them the same as in `UIProgressView`. Semantically they accomplish the same job, it's only fitting to call them the same. 

I can send a PR if you are open to this change.

**Comment by darrarski** [comment]
Sorry for not replaying for a long time. I wasn't able to maintain this project anymore, and I am going to archive it to avoid confusions in the future. Code will be still here, feel free to fork it and use, respecting MIT license.
